project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - images
    - styles.css

website:
  title: "Schenone Farms"
  site-url: https://schenonefarms.com
  favicon: favicon.ico
  search: false
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Our Story"
        href: about.qmd
      - text: "Farmers Markets"
        href: markets.qmd
      - text: "Contact"
        href: contactus.qmd
      - text: "Gallery"
        href: gallery.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: false
    page-layout: full
    
     
