project:
  type: website
  output-dir: docs

website:
  title: "Schenone Farms"
  site-url: "https://rsm-dvschenone.github.io/schenonefarms"
  favicon: favicon.ico
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Our Story"
        href: story.qmd
      - text: "Farmers Markets"
        href: markets.qmd
      - text: "Gallery"
        href: gallery.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: false
    page-layout: full
    
     
